// Preloader
const PRELOADER_BACKGROUND = "#29ADFF";
const PRELOADER_LOGO_SCALE_FACTOR = 3;

// Main menu
const MAIN_MENU_PLAY_BUTTON_WIDTH = 300;
const MAIN_MENU_PLAY_BUTTON_HEIGHT = 100;
const MAIN_MENU_LOGO_SCALE_FACTOR = 3;
const MAIN_MENU_PLAY_BUTTON_OFFSET_Y = 250;
const MAIN_MENU_PLAY_BUTTON_FONT_SIZE = "14px";
const MAIN_MENU_PLAY_BUTTON_FONT_FAMILY = "Arial";
const MAIN_MENU_PLAY_BUTTON_TEXT_COLOR = "#fff";
